In [1]:
# 데이터 수집
# 1. 교보문고 검색창에 '데이터' 검색
# 2. 창에서 F12를 눌러 마지막 페이지 번호 정보의 tag를 가져와 bs.select로 정보를 가져옴
# 3. 같은 방법으로 책제목, 장르, 단가, 평점, 리뷰수 정보의 tag를 가져옴
# 4. 같은 인덱스끼리 합
# zip()을 이용해 동일한 개수로 이루어진 자료형을 묶어 list()를 통해 리스트로 만듬
# 5. 데이터 프레임에 저장하기 위해 2차원 리스트로 저장
# 6. 데이터프레임으로 변환한 뒤 저장 

import math 
import pandas as pd 
from urllib.request import urlopen
from bs4 import BeautifulSoup

# 도서 검색결과의 전체 페이지 결과를 불러오기 위한 마지막 페이지 번호 계산
html=urlopen('https://search.kyobobook.co.kr/web/search?vPstrKeyWord=%25EB%258D%25B0%25EC%259D%25B4%25ED%2584%25B0&orderClick=LAG')
bs=BeautifulSoup(html,'html.parser')
total=bs.select_one('#searchCategory_1 > small')
pages=int(total.text.replace(',',''))/20
pages=math.ceil(pages) 

total_titles=[]
total_genres=[]
total_prices=[]
total_ratings=[]
total_reviews=[]
total_tags = []
for i in range(1,pages+1):
    print(f'page {i}')
    html=urlopen(f'https://search.kyobobook.co.kr/web/search?vPstrKeyWord=%25EB%258D%25B0%25EC%259D%25B4%25ED%2584%25B0&vPstrTab=PRODUCT&searchPcondition=1&currentPage={i}&orderClick=LAG')
    bs=BeautifulSoup(html,'html.parser')
    title=bs.select('td.detail > div.title > a > strong') #책제목
    genre=bs.select('td.detail > div.title > a > span.category2') #장르
    price=bs.select('td.price > div.org_price > del') #정가
    rating=bs.select('tr > td.info > div.review.klover > a > b') # 평점
    reviews = bs.select('tr > td.info > div.review.booklog > a > b') #리뷰수 
    tags = bs.select('tr > td.detail > div.tag') #태그

    total_titles += title 
    total_genres += genre 
    total_prices += price
    total_ratings += rating 
    total_reviews += reviews
    total_tags +=tags



#같은 인덱스끼리 합치기
books=list(zip(total_titles, total_genres, total_prices, total_ratings, total_reviews, total_tags))
print(len(books))

#데이터프레임에 저장하기 위하여 2차원 리스트로 저장
items=[]
for book in books:
    items.append([book[0].text.strip(),book[1].text.strip().replace('[','').replace(']',''),book[2].text.strip(),book[3].text.strip(),book[4].text.strip(), book[5].text.strip()])

#데이터 프레임으로 변환
df=pd.DataFrame(items, columns=['도서명','카테고리','정가','평점','리뷰수','태그'])

#데이터 프레임 저장
df.to_csv('BookReviews.csv', encoding='ms949')

page 1
page 2
page 3
page 4
page 5
page 6
page 7
page 8
page 9
page 10
page 11
page 12
page 13
page 14
page 15
page 16
page 17
page 18
page 19
page 20
page 21
page 22
page 23
page 24
page 25
page 26
page 27
page 28
page 29
page 30
page 31
page 32
page 33
page 34
page 35
page 36
page 37
page 38
page 39
page 40
page 41
page 42
page 43
page 44
page 45
page 46
page 47
page 48
page 49
page 50
page 51
page 52
page 53
page 54
page 55
page 56
page 57
page 58
page 59
page 60
page 61
page 62
page 63
page 64
page 65
page 66
page 67
page 68
page 69
page 70
page 71
page 72
page 73
page 74
page 75
page 76
page 77
page 78
page 79
page 80
page 81
page 82
page 83
page 84
page 85
page 86
page 87
page 88
page 89
page 90
page 91
page 92
page 93
page 94
page 95
page 96
page 97
page 98
page 99
page 100
page 101
page 102
page 103
page 104
page 105
page 106
page 107
page 108
page 109
page 110
page 111
page 112
page 113
page 114
page 115
page 116
page 117
page 118
page 119
page 120
page 121
page 122
page 123
page 124
page 125
page 126
page 127
page 128
page 129
page 130
page 131
page 132
page 133
page 134
page 135
page 136
page 137
page 138
page 139
page 140
page 141
page 142
page 143
page 144
page 145
page 146
page 147
page 148
page 149
page 150
page 151
page 152
page 153
page 154
page 155
page 156
page 157
page 158
page 159
page 160
page 161
page 162
page 163
page 164
page 165
page 166
page 167
page 168
page 169
page 170
page 171
page 172
page 173
page 174
page 175
page 176
page 177
page 178
page 179
page 180
page 181
page 182
page 183
page 184
page 185
page 186
page 187
page 188
page 189
page 190
page 191
page 192
page 193
page 194
page 195
page 196
page 197
page 198
page 199
page 200
page 201
page 202
page 203
page 204
page 205
page 206
page 207
page 208
page 209
page 210
page 211
page 212
page 213
page 214
page 215
page 216
page 217
page 218
page 219
page 220
page 221
page 222
page 223
page 224
page 225
page 226
page 227
page 228
page 229
page 230
page 231
page 232
page 233
page 234
page 235
page 236
page 237
4150

,도서명,카테고리,정가,평점,리뷰수,태그
0,변화하는 세계 질서,경제/경영,"38,000",9.5,9,#빅사이클 #내부질서 #혼란 #투자 #작동원리 #미래전망 #분석자료
1,2022 ADsP 데이터 분석 준전문가,컴퓨터/IT,"28,000",9.2,0,#모의고사 #인사이트 #마이닝
2,나는 대출 없이 0원으로 소형 아파트를 산다,경제/경영,"20,000",9.4,14,#현금흐름표 #실거주 #포트폴리오 #절세 #노하우 #빅데이터 #공급량 #원칙 #지표분석
3,진짜 쓰는 실무 엑셀,컴퓨터/IT,"21,000",9.4,5,#쿼리 #피벗 테이블 #슬라이
4,데이터로 경험을 디자인하라,경제/경영,"19,000",9.0,9,#인사이트 #프레임워크 #잠재니즈 #입체적사고 #디자인씽킹 #라이프분석

In [2]:
df.shape

(4150, 6)

In [3]:
df.head(10)

,도서명,카테고리,정가,평점,리뷰수,태그
0,변화하는 세계 질서,경제/경영,"38,000",9.5,9,#빅사이클 #내부질서 #혼란 #투자 #작동원리 #미래전망 #분석자료
1,2022 ADsP 데이터 분석 준전문가,컴퓨터/IT,"28,000",9.2,0,#모의고사 #인사이트 #마이닝
2,나는 대출 없이 0원으로 소형 아파트를 산다,경제/경영,"20,000",9.4,14,#현금흐름표 #실거주 #포트폴리오 #절세 #노하우 #빅데이터 #공급량 #원칙 #지표분석
3,진짜 쓰는 실무 엑셀,컴퓨터/IT,"21,000",9.4,5,#쿼리 #피벗 테이블 #슬라이
4,데이터로 경험을 디자인하라,경제/경영,"19,000",9.0,9,#인사이트 #프레임워크 #잠재니즈 #입체적사고 #디자인씽킹 #라이프분석
5,그냥 하지 말라 10만부 기념 리커버에디션(색상랜덤),경제/경영,"17,000",9.6,3,#자본 #미래상 #빅데이터
6,SQL 자격검정 실전문제,컴퓨터/IT,"18,000",9.6,0,#고급 활용 #국가 공인 #아키텍처
7,비전공자를 위한 이해할 수 있는 IT 지식,컴퓨터/IT,"16,800",8.6,3,#IT기본문법 #프로그래밍언어 #운영체제 #네트워크 #API #JSON #데이터베이...
8,2022 수제비 정보처리기사 필기 1권+2권 합본세트,컴퓨터/IT,"36,500",9.7,0,#프로시저 #소프트웨어 설계 #데이터베이스 구축
9,Do it! 쉽게 배우는 파이썬 데이터 분석,컴퓨터/IT,"23,000",10,1,#프로그래밍 #튜플 #딕셔너리